export const getGeoLocationConstants ={
    GET_GEO_LOCATION_REQUEST:"GET_GEO_LOCATION_REQUEST",
    GET_GEO_LOCATION_SUCCESS:"GET_GEO_LOCATION_SUCCESS",
    GET_GEO_LOCATION_FAILURE:"GET_GEO_LOCATION_FAILURE",
}
export const getCityLocationConstants ={
    GET_CITY_LOCATION_REQUEST:"GET_CITY_LOCATION_REQUEST",
    GET_CITY_LOCATION_SUCCESS:"GET_CITY_LOCATION_SUCCESS",
    GET_CITY_LOCATION_FAILURE:"GET_CITY_LOCATION_FAILURE",
}
export const getCollectionConstants ={
    GET_COLLECTIONS_REQUEST:"GET_COLLECTIONS_REQUEST",
    GET_COLLECTIONS_SUCCESS:"GET_COLLECTIONS_SUCCESS",
    GET_COLLECTIONS_FAILURE:"GET_COLLECTIONS_FAILURE",
}

export const getRestaurantsListConstants ={
    GET_RESTAURANTS_REQUEST:"GET_RESTAURANTS_REQUEST",
    GET_RESTAURANTS_SUCCESS:"GET_RESTAURANTS_SUCCESS",
    GET_RESTAURANTS_FAILURE:"GET_RESTAURANTS_FAILURE",
}
export const getRestaurant ={
    GET_RESTAURANT_REQUEST:"GET_RESTAURANT_REQUEST",
    GET_RESTAURANT_SUCCESS:"GET_RESTAURANT_SUCCESS",
    GET_RESTAURANT_FAILURE:"GET_RESTAURANT_FAILURE",
}